Httpsession requests typing
locustio/locust pull request #2699
Opened 2024-05-04 22:54 UTC by tdadela

The aim of this PR is to provide better typing annotation support for `class HttpSession`.
This should also fix #2563.

2024-05-05 11:09 UTC, tdadela commented
This PR is still not finished (in draft). Requires adding similar annotations to FastHttpSession and more testing.
It would be nice and beneficial if you @cyberw could express if you are happy with this direction of changes.

2024-05-05 18:27 UTC, cyberw commented
I’ll have a look!

2024-05-05 20:40 UTC, cyberw commented
Is it possible to put all the override definitions in a if typing-block as well? I'd like to avoid the extra level of indirection at run time.

2024-05-05 21:14 UTC, tdadela commented
I'm not 100% sure, but according to my current understanding of Python typing ecosystem — no.
I'll do more research about it.

> I'd like to avoid the extra level of indirection at run time.

What is the main reason behind it?
Easier debugging / performance — necessity to create extra stack frame for additional function call / something else?


Source code of methods in the base class is very short:
```py
    def get(self, url, **kwargs):
        kwargs.setdefault("allow_redirects", True)
        return self.request("GET", url, **kwargs)

    def options(self, url, **kwargs):
        kwargs.setdefault("allow_redirects", True)
        return self.request("OPTIONS", url, **kwargs)

    def head(self, url, **kwargs):
        kwargs.setdefault("allow_redirects", False)
        return self.request("HEAD", url, **kwargs)

    def post(self, url, data=None, json=None, **kwargs):
        return self.request("POST", url, data=data, json=json, **kwargs)

    def put(self, url, data=None, **kwargs):
        return self.request("PUT", url, data=data, **kwargs)

    def patch(self, url, data=None, **kwargs):
        return self.request("PATCH", url, data=data, **kwargs)

    def delete(self, url, **kwargs):
        return self.request("DELETE", url, **kwargs)
```

What do you think about following possible implementation in Locust:
```py
    def get(self, url: str | bytes, **kwargs: Unpack[RESTKwargs]):  # type: ignore[override]
         kwargs.setdefault("allow_redirects", True)
        return self.request("GET", url, **kwargs)  # type: ignore[misc]
```
The number of function call would remain the same.

2024-05-05 21:47 UTC, cyberw commented
Yes, I’m mostly thinking about runtime performance. Why doesnt it work to define the wrappers in an if-block?

2024-05-05 22:11 UTC, tdadela commented
I think about it as defining types of method that de facto doesn't exist (in contrast to a function with the same name in a base class).
I doubt if type checkers were designed to handle such cases.
But I'm just guessing. I don't know.
I'm going to check it.

2024-06-04 18:52 UTC, cyberw commented
hi @tdadela did you have a chance to try it out? Or should I try it?

2024-06-06 14:53 UTC, tdadela commented
I will do it this weekend.

On Tue, 4 Jun 2024, 20:53 Lars Holmberg, ***@***.***> wrote:

> hi @tdadela <https://github.com/tdadela> did you have a chance to try it
> out? Or should I try it?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/locustio/locust/pull/2699#issuecomment-2148195004>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJM4KUOWQAYPRYWYS4S7BMLZFYEJ3AVCNFSM6AAAAABHHFTPXCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNBYGE4TKMBQGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-06-18 21:09 UTC, tdadela commented
Sorry for the delay.
I tried defining HttpSession with annotations, inside if TYPE_CHECKING. It was ignored by type checkers. 

I see 3 options:
1. Keeping HttpSession as is. (no changes, closing PR)
2. Trying to define HttpSession with annotations in a .pyc file.
3. Calling self.requests directly inside HttpSession REST methods (proposition implemented in the last commit). This doesn't increase the number of function calls.

2024-06-18 21:37 UTC, cyberw commented
I like the version in the PR now. Have you tried it with vscode/pyright?

Maybe add a constraint to the typing_extensions dependency to only download it on Python versions <3.11?

2024-06-20 15:23 UTC, 0scarB commented
Hi, I'm using **pyright** 1.1.338 in NeoVim. (With Python version 3.12.3). tdadela's version seems to work great. The `catch_response` and `name` kwargs weren't type hinted correctly before, now they are. Some screenshots:
![image](https://github.com/locustio/locust/assets/28349560/8113f636-ea22-4d12-8101-fad4d214ccfe)
![image](https://github.com/locustio/locust/assets/28349560/081a8c82-59c2-45de-a549-4c5eb81a4dbe)

Hope this helps. Thanks for the awesome project and great work tdadela!

2024-06-20 16:43 UTC, 0scarB requested changes

2024-06-20 16:43 UTC, 0scarB commented on locust/clients.py
> +    def post(self, url: str | bytes, data: Any | None = None, json: Any | None = None, **kwargs: Unpack[RESTKwargs]):  # type: ignore[override, misc]
There does seem to be a problem when using pyright after all. For HTTP methods where  `data=data` and/or `json=json` is passed to `self.request(...)` the return type becomes `Unknown`
![image](https://github.com/locustio/locust/assets/28349560/720c3a67-4d09-497c-a180-f15e7b00a2ea)

I'm unsure what causes this behaviour. Explicitly providing the return type seems to fix it (see suggested changes).

```suggestion
    def post(self, url: str | bytes, data: Any | None = None, json: Any | None = None, **kwargs: Unpack[RESTKwargs]) -> (ResponseContextManager | Response | LocustResponse):  # type: ignore[override, misc]
```

Now the correct return type is shown:
![image](https://github.com/locustio/locust/assets/28349560/25b25044-7a6a-4a56-ac73-fb780c13105a)

2024-06-20 16:43 UTC, 0scarB commented on locust/clients.py
> +    def put(self, url: str | bytes, data: Any | None = None, **kwargs: Unpack[RESTKwargs]):  # type: ignore[override, misc]
```suggestion
    def put(self, url: str | bytes, data: Any | None = None, **kwargs: Unpack[RESTKwargs]) -> (ResponseContextManager | Response | LocustResponse):   # type: ignore[override, misc]
```

2024-06-20 16:43 UTC, 0scarB commented on locust/clients.py
> +    def patch(self, url: str | bytes, data: Any | None = None, **kwargs: Unpack[RESTKwargs]):  # type: ignore[override, misc]
```suggestion
     def patch(self, url: str | bytes, data: Any | None = None, **kwargs: Unpack[RESTKwargs]) -> (ResponseContextManager | Response | LocustResponse):  # type: ignore[override, misc]
```

2024-06-23 21:39 UTC, tdadela commented
@cyberw Do you prefer the last or the last but one version?
(I'll fix the stupid mistake in a minute)

Also, I've realized that  # type: ignore[misc] is no longer necessary, probably since calling self.request directly. I'll remove it later. (To not make the impression it's connected with the last commit).

2024-06-23 22:09 UTC, tdadela commented
> Have you tried it with vscode/pyright?

Yes. It works well.  (I hope I checked everything correctly.)

2024-06-23 22:27 UTC, tdadela commented
@0scarB Thank you very much for your support!
It's especially beneficial since I don't use some tools, e.g., pyright on daily bases (I'm not sure if I test everything correctly).

2024-06-24 08:46 UTC, 0scarB commented
> @0scarB Thank you very much for your support! It's especially beneficial since I don't use some tools, e.g., pyright on daily bases (I'm not sure if I test everything correctly).

Tested the latest commit in my project. LGTM! The return types are now correct. Happy to help

2024-06-24 09:26 UTC, cyberw commented
Looks good to me too. @tdadela If you feel it is ready to go, move it out of draft and I'll merge it. Ideally I'd like to use the same typing for FastHttpSession but we can do that later on...

2024-06-24 19:39 UTC, tdadela commented
Today I tried to make return type argument dependent (catch_response) using `@overload`. Unfortunately, this makes the file super clutter.

> Ideally I'd like to use the same typing for FastHttpSession but we can do that later on...

Yup, soon in another PR.

2024-06-25 08:52 UTC, merged